
services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend  

  frontend-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - CI=true
      - REACT_APP_API_URL=http://frontend-test:5000
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  cypress:
    image: cypress/included:13.6.0
    working_dir: /e2e
    volumes:
      - .:/e2e
    environment:
      - CYPRESS_baseUrl=http://frontend:3000
    depends_on:
      - frontend
      - backend

volumes:
  mongo_data:
